### PR TITLE
Finegrained humidity

### PR DESCRIPTION
**Pull request by chbw**
Humidity in ENV_DATA has the same format as temperature, but without the offset. This pull request adapts setEnvironmentalData() to take humidity as a double as well. In addition to basically duplicating the code for temperature it also changes the division by 0.001953125 to a multiplication by 512. Mathematically this works out to be exactly the same, but it feels more in line with the datasheet which specifies "[...] is stored as an unsigned 16 bits integer in 1/512 [...]".
Additionally: I used "clang-format -i" this time _before_ submitting the pull request :-)

### CODE REVIEW

**Comment by ladyada** [comment]
please change to float, we dont get double preceision anyways

**Comment by chbw** [comment]
Both humidity and temperature?

**Comment by ladyada** [comment]
yes please, will reduce flash usage greatly - we shouldn't be using doubles

**Comment by chbw** [comment]
modf won't work with floats :-(

**Comment by chbw** [comment]
The "algorithm" to convert the float values to uint16_t has been verified with the following code snippet (on a linux box):
````
#include <stdint.h>
#include <stdio.h>

int main(void) {
  float hum = 48.75;
  uint16_t hum_conv = hum * 512 + 0.5;

  printf("%g\n", hum);
  printf("%x\n", hum_conv);
  return 0;
}
````
result:
````
[chbw@undisclosed ccs811test]$ g++ foo.cpp -o foo && ./foo
48.75
6180
````

**Comment by chbw** [comment]
I added the `f`-suffix to the constants to _really_ avoid doubles.

While the previous code version only explicitly uses `float`, the constants without suffix _can_ cause an implicit conversion to `double`. With [ARM gcc 9.2 (none) on compiler explorer/godbolt.org](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:c%2B%2B,selection:(endColumn:35,endLineNumber:17,positionColumn:35,positionLineNumber:17,selectionStartColumn:35,selectionStartLineNumber:17,startColumn:35,startLineNumber:17),source:'%23include+%3Cstdint.h%3E%0A%0Auint16_t+convhf(float+hum+%3D+48.75)+%7B%0A++++return+hum+*+512.0f+%2B+0.5f%3B%0A%7D%0A%0Auint16_t+convh(float+hum+%3D+48.75)+%7B%0A++++return+hum+*+512+%2B+0.5%3B%0A%7D%0A%0A%0Auint16_t+convtf(float+temp+%3D+25.5)+%7B%0A++++return+(temp+%2B+25.0f)+*+512.0f+%2B+0.5f%3B%0A%7D%0A%0Auint16_t+convt(float+temp+%3D+25.5)+%7B%0A++++return+(temp+%2B+25)+*+512+%2B+0.5%3B%0A%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:arm921,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'1',trim:'1'),fontScale:14,j:1,lang:c%2B%2B,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'ARM+gcc+9.2.1+(none)+(Editor+%231,+Compiler+%231)+C%2B%2B',t:'0')),k:50,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4) one can see that the variant _without_ the `f` suffix uses `__aeabi_f2d`, `__aeabi_dadd` and `__aeabi_d2uiz` where _with_ the suffix no conversion to double takes places and the code only uses `__aeabi_fadd` and `__aeabi_f2uiz`. However, there is no difference between the variants with AVR gcc 9.2.0 where float and double are literally the same.

**Comment by ladyada** [comment]
thanks! @caternuson can you take a look?

**Comment by caternuson** [comment]
@ladyada :eyes: yep

@chbw Is this changed based only on code inspection? Or is there some repeatable issue that goes along with this?

**Comment by chbw** [comment]
@caternuson this is not based only on code inspection, this is working code. I wanted to use the full precision of a DHT22 sensor's humidity data with the CCS811 ENV_DATA register.

The first commit here (1e1e4ff) basically duplicated the code for temperature (due to the very similar format in the registers) and the humidity parameter got the same data type as the temperature parameter. A very conservative (or lazy?) code change.

In the second commit (28fb189), I tried to get rid of `double` in favor of  #`float` after @ladyada's input. Unfortunately, simply replacing `double` with `float` did not cut it. The function `modf` in the existing code takes a pointer to a double as second argument, which necessitates having a double in the first place. So I implemented the conversion in a different way. While being functionally correct, commit 28fb189 is a major mistake at it still contains double literals and thus does not get rid of `double` induced code at all.

Commit e0a6a8e finally contains float literals.

**Comment by caternuson** [comment]
Thanks for this. Looks like a good update. The existing implementation does look a bit odd - both in parameter types used and not using full resolution of relative humidity.

Tested the update with simple modification to library example sketch:
```cpp
#include "Adafruit_CCS811.h"

Adafruit_CCS811 ccs;

void setup() {
  Serial.begin(9600);
  while (!Serial);

  Serial.println("CCS811 test");

  if(!ccs.begin()){
    Serial.println("Failed to start sensor! Please check your wiring.");
    while(1);
  }

  // Wait for the sensor to be ready
  while(!ccs.available());

  // Set known values for humidity and temperature
  ccs.setEnvironmentalData(42.8, 24.3);
}

void loop() {
  if(ccs.available()){
    if(!ccs.readData()){
      Serial.print("CO2: ");
      Serial.print(ccs.geteCO2());
      Serial.print("ppm, TVOC: ");
      Serial.println(ccs.getTVOC());
    }
    else{
      Serial.println("ERROR!");
      while(1);
    }
  }
  delay(500);
}
```
on an Itsy M4 and simple breath-on-it for input:
```
CCS811 test
CO2: 0ppm, TVOC: 0
CO2: 0ppm, TVOC: 0
CO2: 0ppm, TVOC: 0
CO2: 400ppm, TVOC: 0
CO2: 746ppm, TVOC: 52
CO2: 746ppm, TVOC: 52
```

Dumping relevant datasheet info here for general reference:
ccs811_env

**Review by caternuson — APPROVED** [review]

**Pull request merged**
